[package]
name = "hash_sign_dapp"
version = "1.0.0"

[addresses]
HashSign="Put your wallet address here"
aptos_framework = "0x1"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
